# Generated by Django 4.2.14 on 2025-09-28 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The feedback content')),
                ('username', models.CharField(help_text='Who posted this feedback', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When feedback was created')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Who voted', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='feedback.feedback')),
            ],
            options={
                'unique_together': {('feedback', 'username')},
            },
        ),
    ]
